/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectToClientScreen.java
 *
 * Created on Apr 13, 2010, 11:02:56 AM
 */

package interactiveclassroom;

import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
class NewThread extends Thread
{
    Thread T;
    String ip;

    public NewThread(String d_ip)
    {
        ip = d_ip;
        T = new Thread(this,"Child Thread");
        T.start();
    }

    public void run()
    {
        try
        {
            String s[] = new String[5];
            s[0]=ip;
            ScreenCaptureThread.main(s);
        }
        catch(InterruptedException ie)
        {
            System.out.println("New Thread Error::: "+ie);
        }
        catch(Exception e)
        {
            System.out.println("New Thread Error::: "+e);
        }
    }
}


public class ConnectToClientScreen extends javax.swing.JFrame {

    /** Creates new form ConnectToClientScreen */
    String clientIP;

    public ConnectToClientScreen() {
        initComponents();

        /*int i=0;
        while(i<mainHome.cip)
        {
            jcmbClient.insertItemAt(mainHome.ll.get(i),i);
            System.out.println("MC "+i+": "+mainHome.ll.get(i));
            i++;
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcmbClient = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtfPort = new javax.swing.JTextField();
        jbConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connect to Client");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Client IP");

        jcmbClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcmbClientFocusGained(evt);
            }
        });

        jLabel2.setText("Port No");

        jtfPort.setEditable(false);
        jtfPort.setText("3232");

        jbConnect.setText("Connect");
        jbConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcmbClient, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbConnect)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConnect)
                    .addComponent(jcmbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectActionPerformed
        // TODO add your handling code here:

        jtfPort.setText("3232");

        try
        {
            clientIP = jcmbClient.getSelectedItem().toString();

            mainHome.CSCapt = true;
            new NewThread(clientIP);
        }
        catch(Exception ne) {
            System.out.println("Exception : " + ne);
            JOptionPane.showMessageDialog(this,"Please Select The Valid Client IP Adress !!!");
        }

    }//GEN-LAST:event_jbConnectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void jcmbClientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcmbClientFocusGained
        // TODO add your handling code here:

        jcmbClient.removeAllItems();
        int i=0;
        while(i<mainHome.cip)
        {
            jcmbClient.insertItemAt(mainHome.ll.get(i),i);
            System.out.println("MC "+i+": "+mainHome.ll.get(i));
            i++;
        }
    }//GEN-LAST:event_jcmbClientFocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectToClientScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbConnect;
    private javax.swing.JComboBox jcmbClient;
    private javax.swing.JTextField jtfPort;
    // End of variables declaration//GEN-END:variables

}
