/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShutDownGui.java
 *
 * Created on Mar 10, 2010, 4:11:10 PM
 */

package interactiveclassroom;

import javax.swing.JOptionPane;
import java.rmi.registry.*;
import java.rmi.*;

/**
 *
 * @author Ahesan_for_S
 */
public class ShutDownGui extends javax.swing.JFrame {

    /** Creates new form ShutDownGui */
    int choise;
    String cmd;

    public ShutDownGui()
    {
        initComponents();

        /*int i=0;
        while(i<mainHome.cip)
        {
            jcmbSD.insertItemAt(mainHome.ll.get(i),i);
            System.out.println("MC "+i+": "+mainHome.ll.get(i));
            i++;
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtPortNo = new javax.swing.JTextField();
        jcmbSD = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jrTurnOff = new javax.swing.JRadioButton();
        jrRestart = new javax.swing.JRadioButton();
        jrLogOff = new javax.swing.JRadioButton();
        jlStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ShutDown");
        setAlwaysOnTop(true);
        setResizable(false);

        jButton1.setText("Perform");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setToolTipText("Text1");

        jLabel1.setText("Client IP Address");

        jLabel2.setText("Port No");

        jtPortNo.setEditable(false);
        jtPortNo.setText("3232");

        jcmbSD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcmbSDFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcmbSD, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buttonGroup1.add(jrTurnOff);
        jrTurnOff.setSelected(true);
        jrTurnOff.setText("Turn Off");

        buttonGroup1.add(jrRestart);
        jrRestart.setText("Restart");

        buttonGroup1.add(jrLogOff);
        jrLogOff.setText("Log Off ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jrTurnOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrRestart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrLogOff)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrRestart)
                        .addComponent(jrLogOff))
                    .addComponent(jrTurnOff))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jlStatus.setText("Status: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Registry registry;
        String ClientAddress="";
        try
        {
            ClientAddress = jcmbSD.getSelectedItem().toString();
            String Port = jtPortNo.getText();
            String remoteURL;
            System.out.println("Selected Client: "+ClientAddress);
        
        
            remoteURL = "rmi://" + ClientAddress + ":" + Port + "/shutdown";
            ShutDownIntf shtcl;
            System.out.println(remoteURL);
            shtcl=(ShutDownIntf)Naming.lookup(remoteURL);

            choise=JOptionPane.showConfirmDialog(this, "Are you Sure?");
            
            if(choise==0)
            {
                if(jrTurnOff.isSelected())
                    shtcl.shutDown();
                
                else if(jrLogOff.isSelected())
                    shtcl.logOff();
                else if(jrRestart.isSelected())
                    shtcl.restart();
            }
        }
        catch(RemoteException re)
        {
            JOptionPane.showMessageDialog(this,"RemoteAgent("+ClientAddress+") is not Ready !!!");
        }
        catch(NotBoundException ne)
        {
            JOptionPane.showMessageDialog(this,"RemoteAgent("+ClientAddress+") is not Ready !!!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"RemoteAgent("+ClientAddress+") is not Ready !!!");
        }

        //yes: 0
        //No:1
        //Cancel: 2
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcmbSDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcmbSDFocusGained
        // TODO add your handling code here:

        jcmbSD.removeAllItems();
        int i=0;
        while(i<mainHome.cip)
        {
            jcmbSD.insertItemAt(mainHome.ll.get(i),i);
            System.out.println("MC "+i+": "+mainHome.ll.get(i));
            i++;
        }
    }//GEN-LAST:event_jcmbSDFocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShutDownGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jcmbSD;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JRadioButton jrLogOff;
    private javax.swing.JRadioButton jrRestart;
    private javax.swing.JRadioButton jrTurnOff;
    private javax.swing.JTextField jtPortNo;
    // End of variables declaration//GEN-END:variables

}
